'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
'
Namespace com.disney.corp.stpga
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PGAWebServiceSoap", [Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class PGAWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetHoleByHoleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPlayersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTournamentsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTeeTimesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApplication1.My.MySettings.Default.WindowsApplication1_com_disney_corp_stpga_PGAWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetHoleByHoleCompleted As GetHoleByHoleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPlayersCompleted As GetPlayersCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTournamentsCompleted As GetTournamentsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTeeTimesCompleted As GetTeeTimesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ESDR.PGA.PGAWebService/GetHoleByHole", RequestNamespace:="ESDR.PGA.PGAWebService", ResponseNamespace:="ESDR.PGA.PGAWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetHoleByHole(ByVal TournamentID As Long) As HoleByHole
            Dim results() As Object = Me.Invoke("GetHoleByHole", New Object() {TournamentID})
            Return CType(results(0),HoleByHole)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetHoleByHoleAsync(ByVal TournamentID As Long)
            Me.GetHoleByHoleAsync(TournamentID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetHoleByHoleAsync(ByVal TournamentID As Long, ByVal userState As Object)
            If (Me.GetHoleByHoleOperationCompleted Is Nothing) Then
                Me.GetHoleByHoleOperationCompleted = AddressOf Me.OnGetHoleByHoleOperationCompleted
            End If
            Me.InvokeAsync("GetHoleByHole", New Object() {TournamentID}, Me.GetHoleByHoleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetHoleByHoleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetHoleByHoleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetHoleByHoleCompleted(Me, New GetHoleByHoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ESDR.PGA.PGAWebService/GetPlayers", RequestNamespace:="ESDR.PGA.PGAWebService", ResponseNamespace:="ESDR.PGA.PGAWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPlayers() As Golfers
            Dim results() As Object = Me.Invoke("GetPlayers", New Object(-1) {})
            Return CType(results(0),Golfers)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPlayersAsync()
            Me.GetPlayersAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPlayersAsync(ByVal userState As Object)
            If (Me.GetPlayersOperationCompleted Is Nothing) Then
                Me.GetPlayersOperationCompleted = AddressOf Me.OnGetPlayersOperationCompleted
            End If
            Me.InvokeAsync("GetPlayers", New Object(-1) {}, Me.GetPlayersOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPlayersOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPlayersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPlayersCompleted(Me, New GetPlayersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ESDR.PGA.PGAWebService/GetTournaments", RequestNamespace:="ESDR.PGA.PGAWebService", ResponseNamespace:="ESDR.PGA.PGAWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTournaments(ByVal Year As String) As TournamentInfo
            Dim results() As Object = Me.Invoke("GetTournaments", New Object() {Year})
            Return CType(results(0),TournamentInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTournamentsAsync(ByVal Year As String)
            Me.GetTournamentsAsync(Year, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTournamentsAsync(ByVal Year As String, ByVal userState As Object)
            If (Me.GetTournamentsOperationCompleted Is Nothing) Then
                Me.GetTournamentsOperationCompleted = AddressOf Me.OnGetTournamentsOperationCompleted
            End If
            Me.InvokeAsync("GetTournaments", New Object() {Year}, Me.GetTournamentsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTournamentsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTournamentsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTournamentsCompleted(Me, New GetTournamentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("ESDR.PGA.PGAWebService/GetTeeTimes", RequestNamespace:="ESDR.PGA.PGAWebService", ResponseNamespace:="ESDR.PGA.PGAWebService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTeeTimes(ByVal TournamentID As Long) As TeeTimes
            Dim results() As Object = Me.Invoke("GetTeeTimes", New Object() {TournamentID})
            Return CType(results(0),TeeTimes)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTeeTimesAsync(ByVal TournamentID As Long)
            Me.GetTeeTimesAsync(TournamentID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTeeTimesAsync(ByVal TournamentID As Long, ByVal userState As Object)
            If (Me.GetTeeTimesOperationCompleted Is Nothing) Then
                Me.GetTeeTimesOperationCompleted = AddressOf Me.OnGetTeeTimesOperationCompleted
            End If
            Me.InvokeAsync("GetTeeTimes", New Object() {TournamentID}, Me.GetTeeTimesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTeeTimesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTeeTimesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTeeTimesCompleted(Me, New GetTeeTimesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class HoleByHole
        
        Private playerField() As HoleByHolePlayer
        
        Private tournamentidField As String
        
        Private statusField As String
        
        Private tournNameField As String
        
        Private leaderboardMessageField As String
        
        Private cutRndField As String
        
        Private cutCountField As String
        
        Private cutScoreField As String
        
        Private currentRoundField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("player")>  _
        Public Property player() As HoleByHolePlayer()
            Get
                Return Me.playerField
            End Get
            Set
                Me.playerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tournamentid() As String
            Get
                Return Me.tournamentidField
            End Get
            Set
                Me.tournamentidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TournName() As String
            Get
                Return Me.tournNameField
            End Get
            Set
                Me.tournNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property LeaderboardMessage() As String
            Get
                Return Me.leaderboardMessageField
            End Get
            Set
                Me.leaderboardMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CutRnd() As String
            Get
                Return Me.cutRndField
            End Get
            Set
                Me.cutRndField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CutCount() As String
            Get
                Return Me.cutCountField
            End Get
            Set
                Me.cutCountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CutScore() As String
            Get
                Return Me.cutScoreField
            End Get
            Set
                Me.cutScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CurrentRound() As String
            Get
                Return Me.currentRoundField
            End Get
            Set
                Me.currentRoundField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class HoleByHolePlayer
        
        Private roundField() As Round
        
        Private playeridField As Long
        
        Private firstnameField As String
        
        Private lastnameField As String
        
        Private currentpositionField As Integer
        
        Private currentroundField As Integer
        
        Private currentholeField As Short
        
        Private playerstatusField As String
        
        Private ytdcuppointsstartField As Long
        
        Private ytdcuprankstartField As String
        
        Private ytdcuptrailptsstartField As Long
        
        Private ytdcuppointsprjField As Long
        
        Private ytdcuprankprjField As String
        
        Private ytdcuptrailptsprjField As Long
        
        Private evtcupptsprjField As Long
        
        Private cupbonusmoneyField As Long
        
        Private moneywonField As Long
        
        Private tournparrelField As String
        
        Private tournstrokeField As Long
        
        Private eaglesField As Double
        
        Private birdiesField As Double
        
        Private parsField As Double
        
        Private bogeysField As Double
        
        Private doublesField As Double
        
        Private penaltiesField As Double
        
        Private drivedistavgField As Double
        
        Private fairwayshitField As Double
        
        Private fairwaysoppField As Double
        
        Private longestdriveField As Double
        
        Private girField As Double
        
        Private giroppField As Double
        
        Private puttsgirField As Double
        
        Private avgputtsgirField As Double
        
        Private sandsavesField As Double
        
        Private sandsavesoppField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("round")>  _
        Public Property round() As Round()
            Get
                Return Me.roundField
            End Get
            Set
                Me.roundField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property playerid() As Long
            Get
                Return Me.playeridField
            End Get
            Set
                Me.playeridField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property currentposition() As Integer
            Get
                Return Me.currentpositionField
            End Get
            Set
                Me.currentpositionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property currentround() As Integer
            Get
                Return Me.currentroundField
            End Get
            Set
                Me.currentroundField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property currenthole() As Short
            Get
                Return Me.currentholeField
            End Get
            Set
                Me.currentholeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property playerstatus() As String
            Get
                Return Me.playerstatusField
            End Get
            Set
                Me.playerstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ytdcuppointsstart() As Long
            Get
                Return Me.ytdcuppointsstartField
            End Get
            Set
                Me.ytdcuppointsstartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ytdcuprankstart() As String
            Get
                Return Me.ytdcuprankstartField
            End Get
            Set
                Me.ytdcuprankstartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ytdcuptrailptsstart() As Long
            Get
                Return Me.ytdcuptrailptsstartField
            End Get
            Set
                Me.ytdcuptrailptsstartField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ytdcuppointsprj() As Long
            Get
                Return Me.ytdcuppointsprjField
            End Get
            Set
                Me.ytdcuppointsprjField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ytdcuprankprj() As String
            Get
                Return Me.ytdcuprankprjField
            End Get
            Set
                Me.ytdcuprankprjField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ytdcuptrailptsprj() As Long
            Get
                Return Me.ytdcuptrailptsprjField
            End Get
            Set
                Me.ytdcuptrailptsprjField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property evtcupptsprj() As Long
            Get
                Return Me.evtcupptsprjField
            End Get
            Set
                Me.evtcupptsprjField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cupbonusmoney() As Long
            Get
                Return Me.cupbonusmoneyField
            End Get
            Set
                Me.cupbonusmoneyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property moneywon() As Long
            Get
                Return Me.moneywonField
            End Get
            Set
                Me.moneywonField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tournparrel() As String
            Get
                Return Me.tournparrelField
            End Get
            Set
                Me.tournparrelField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tournstroke() As Long
            Get
                Return Me.tournstrokeField
            End Get
            Set
                Me.tournstrokeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property eagles() As Double
            Get
                Return Me.eaglesField
            End Get
            Set
                Me.eaglesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property birdies() As Double
            Get
                Return Me.birdiesField
            End Get
            Set
                Me.birdiesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pars() As Double
            Get
                Return Me.parsField
            End Get
            Set
                Me.parsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property bogeys() As Double
            Get
                Return Me.bogeysField
            End Get
            Set
                Me.bogeysField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property doubles() As Double
            Get
                Return Me.doublesField
            End Get
            Set
                Me.doublesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property penalties() As Double
            Get
                Return Me.penaltiesField
            End Get
            Set
                Me.penaltiesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property drivedistavg() As Double
            Get
                Return Me.drivedistavgField
            End Get
            Set
                Me.drivedistavgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fairwayshit() As Double
            Get
                Return Me.fairwayshitField
            End Get
            Set
                Me.fairwayshitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fairwaysopp() As Double
            Get
                Return Me.fairwaysoppField
            End Get
            Set
                Me.fairwaysoppField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property longestdrive() As Double
            Get
                Return Me.longestdriveField
            End Get
            Set
                Me.longestdriveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property gir() As Double
            Get
                Return Me.girField
            End Get
            Set
                Me.girField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property giropp() As Double
            Get
                Return Me.giroppField
            End Get
            Set
                Me.giroppField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property puttsgir() As Double
            Get
                Return Me.puttsgirField
            End Get
            Set
                Me.puttsgirField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property avgputtsgir() As Double
            Get
                Return Me.avgputtsgirField
            End Get
            Set
                Me.avgputtsgirField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property sandsaves() As Double
            Get
                Return Me.sandsavesField
            End Get
            Set
                Me.sandsavesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property sandsavesopp() As Double
            Get
                Return Me.sandsavesoppField
            End Get
            Set
                Me.sandsavesoppField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class Round
        
        Private holeField() As Hole
        
        Private round_numberField As Integer
        
        Private courseidField As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("hole")>  _
        Public Property hole() As Hole()
            Get
                Return Me.holeField
            End Get
            Set
                Me.holeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property round_number() As Integer
            Get
                Return Me.round_numberField
            End Get
            Set
                Me.round_numberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property courseid() As Long
            Get
                Return Me.courseidField
            End Get
            Set
                Me.courseidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class Hole
        
        Private numberField As Integer
        
        Private holeidField As Long
        
        Private parField As Integer
        
        Private strokesField As Integer
        
        Private timestampField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property number() As Integer
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property holeid() As Long
            Get
                Return Me.holeidField
            End Get
            Set
                Me.holeidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property par() As Integer
            Get
                Return Me.parField
            End Get
            Set
                Me.parField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property strokes() As Integer
            Get
                Return Me.strokesField
            End Get
            Set
                Me.strokesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property timestamp() As Date
            Get
                Return Me.timestampField
            End Get
            Set
                Me.timestampField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class TeetimePlayer
        
        Private player_idField As Long
        
        Private firstnameField As String
        
        Private lastnameField As String
        
        Private amateurField As String
        
        Private playerstatusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property player_id() As Long
            Get
                Return Me.player_idField
            End Get
            Set
                Me.player_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property amateur() As String
            Get
                Return Me.amateurField
            End Get
            Set
                Me.amateurField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property playerstatus() As String
            Get
                Return Me.playerstatusField
            End Get
            Set
                Me.playerstatusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class TeeTime
        
        Private golferField() As TeetimePlayer
        
        Private courseidField As Long
        
        Private roundField As Integer
        
        Private startteeField As Integer
        
        Private groupField As Integer
        
        Private teedatetimeField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("golfer")>  _
        Public Property golfer() As TeetimePlayer()
            Get
                Return Me.golferField
            End Get
            Set
                Me.golferField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property courseid() As Long
            Get
                Return Me.courseidField
            End Get
            Set
                Me.courseidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property round() As Integer
            Get
                Return Me.roundField
            End Get
            Set
                Me.roundField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property starttee() As Integer
            Get
                Return Me.startteeField
            End Get
            Set
                Me.startteeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property group() As Integer
            Get
                Return Me.groupField
            End Get
            Set
                Me.groupField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property teedatetime() As Date
            Get
                Return Me.teedatetimeField
            End Get
            Set
                Me.teedatetimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class TeeTimes
        
        Private teetimeField() As TeeTime
        
        Private tournamentidField As String
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("teetime")>  _
        Public Property teetime() As TeeTime()
            Get
                Return Me.teetimeField
            End Get
            Set
                Me.teetimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tournamentid() As String
            Get
                Return Me.tournamentidField
            End Get
            Set
                Me.tournamentidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class Course
        
        Private course_idField As Long
        
        Private pgacourse_idField As Long
        
        Private nameField As String
        
        Private acronymField As String
        
        Private parField As Integer
        
        Private yardsField As Long
        
        Private par_inField As Integer
        
        Private par_outField As Integer
        
        Private locationField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property course_id() As Long
            Get
                Return Me.course_idField
            End Get
            Set
                Me.course_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pgacourse_id() As Long
            Get
                Return Me.pgacourse_idField
            End Get
            Set
                Me.pgacourse_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property acronym() As String
            Get
                Return Me.acronymField
            End Get
            Set
                Me.acronymField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property par() As Integer
            Get
                Return Me.parField
            End Get
            Set
                Me.parField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property yards() As Long
            Get
                Return Me.yardsField
            End Get
            Set
                Me.yardsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property par_in() As Integer
            Get
                Return Me.par_inField
            End Get
            Set
                Me.par_inField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property par_out() As Integer
            Get
                Return Me.par_outField
            End Get
            Set
                Me.par_outField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class Tournament
        
        Private courseField() As Course
        
        Private tourn_idField As Long
        
        Private nameField As String
        
        Private pgatourn_idField As String
        
        Private event_idField As String
        
        Private formatField As String
        
        Private start_dateField As Date
        
        Private end_dateField As Date
        
        Private purseField As Long
        
        Private roundsField As Integer
        
        Private locationField As String
        
        Private statusField As String
        
        Private typeField As String
        
        Private timezoneField As String
        
        Private host_course_idField As String
        
        Private defchampidField As String
        
        Private gmtoffsetField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("course")>  _
        Public Property course() As Course()
            Get
                Return Me.courseField
            End Get
            Set
                Me.courseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property tourn_id() As Long
            Get
                Return Me.tourn_idField
            End Get
            Set
                Me.tourn_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pgatourn_id() As String
            Get
                Return Me.pgatourn_idField
            End Get
            Set
                Me.pgatourn_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property event_id() As String
            Get
                Return Me.event_idField
            End Get
            Set
                Me.event_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
        Public Property start_date() As Date
            Get
                Return Me.start_dateField
            End Get
            Set
                Me.start_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
        Public Property end_date() As Date
            Get
                Return Me.end_dateField
            End Get
            Set
                Me.end_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property purse() As Long
            Get
                Return Me.purseField
            End Get
            Set
                Me.purseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property rounds() As Integer
            Get
                Return Me.roundsField
            End Get
            Set
                Me.roundsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property timezone() As String
            Get
                Return Me.timezoneField
            End Get
            Set
                Me.timezoneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property host_course_id() As String
            Get
                Return Me.host_course_idField
            End Get
            Set
                Me.host_course_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property defchampid() As String
            Get
                Return Me.defchampidField
            End Get
            Set
                Me.defchampidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property gmtoffset() As String
            Get
                Return Me.gmtoffsetField
            End Get
            Set
                Me.gmtoffsetField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class TournamentInfo
        
        Private tournamentField() As Tournament
        
        Private yearField As String
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("tournament")>  _
        Public Property tournament() As Tournament()
            Get
                Return Me.tournamentField
            End Get
            Set
                Me.tournamentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property year() As String
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class Golfer
        
        Private player_idField As Long
        
        Private firstnameField As String
        
        Private middlenameField As String
        
        Private lastnameField As String
        
        Private heightField As String
        
        Private weightField As Integer
        
        Private handField As String
        
        Private statusField As String
        
        Private collegeField As String
        
        Private birthcityField As String
        
        Private birthstateField As String
        
        Private birthcountryField As String
        
        Private birthdateField As Date
        
        Private prodebutyearField As String
        
        Private amateurField As String
        
        Private active_leagueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property player_id() As Long
            Get
                Return Me.player_idField
            End Get
            Set
                Me.player_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property firstname() As String
            Get
                Return Me.firstnameField
            End Get
            Set
                Me.firstnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property middlename() As String
            Get
                Return Me.middlenameField
            End Get
            Set
                Me.middlenameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property lastname() As String
            Get
                Return Me.lastnameField
            End Get
            Set
                Me.lastnameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property height() As String
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property weight() As Integer
            Get
                Return Me.weightField
            End Get
            Set
                Me.weightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property hand() As String
            Get
                Return Me.handField
            End Get
            Set
                Me.handField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property college() As String
            Get
                Return Me.collegeField
            End Get
            Set
                Me.collegeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property birthcity() As String
            Get
                Return Me.birthcityField
            End Get
            Set
                Me.birthcityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property birthstate() As String
            Get
                Return Me.birthstateField
            End Get
            Set
                Me.birthstateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property birthcountry() As String
            Get
                Return Me.birthcountryField
            End Get
            Set
                Me.birthcountryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="date")>  _
        Public Property birthdate() As Date
            Get
                Return Me.birthdateField
            End Get
            Set
                Me.birthdateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="gYear")>  _
        Public Property prodebutyear() As String
            Get
                Return Me.prodebutyearField
            End Get
            Set
                Me.prodebutyearField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property amateur() As String
            Get
                Return Me.amateurField
            End Get
            Set
                Me.amateurField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property active_league() As String
            Get
                Return Me.active_leagueField
            End Get
            Set
                Me.active_leagueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="ESDR.PGA.PGAWebService")>  _
    Partial Public Class Golfers
        
        Private playerField() As Golfer
        
        Private statusField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("player")>  _
        Public Property player() As Golfer()
            Get
                Return Me.playerField
            End Get
            Set
                Me.playerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetHoleByHoleCompletedEventHandler(ByVal sender As Object, ByVal e As GetHoleByHoleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetHoleByHoleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As HoleByHole
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),HoleByHole)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetPlayersCompletedEventHandler(ByVal sender As Object, ByVal e As GetPlayersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPlayersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Golfers
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Golfers)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetTournamentsCompletedEventHandler(ByVal sender As Object, ByVal e As GetTournamentsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTournamentsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TournamentInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TournamentInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetTeeTimesCompletedEventHandler(ByVal sender As Object, ByVal e As GetTeeTimesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTeeTimesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TeeTimes
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TeeTimes)
            End Get
        End Property
    End Class
End Namespace
